package com.marcosmoreiradev.docupodcaststudio.application.modelsetup;

import com.marcosmoreiradev.docupodcaststudio.application.runtime.RuntimeArtifactPaths;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;

/** Inspects the last local proof WAV generated by Voz IA avanzada from the app runtime layout. */
public final class InspectXttsSmokeTestUseCase {
    public XttsSmokeTestReport inspect(Path applicationRoot) {
        Path root = applicationRoot == null ? Path.of(".").toAbsolutePath().normalize() : applicationRoot.toAbsolutePath().normalize();
        Path dir = smokeDirectory(root);
        Path text = dir.resolve("xtts-readiness-smoke.txt");
        Path audio = dir.resolve("xtts-readiness-smoke.wav");
        Path manifest = RuntimeArtifactPaths.fromRoot(root).xttsReadinessSmokeManifest();
        if (!Files.isRegularFile(manifest) || !Files.isRegularFile(audio)) {
            return XttsSmokeTestReport.pending(dir, "Falta generar una prueba WAV real de Voz IA avanzada desde Configuracion.");
        }
        try {
            long bytes = Files.size(audio);
            String json = Files.readString(manifest, StandardCharsets.UTF_8);
            boolean generated = json.contains("\"generated\": true") && bytes > 44L;
            boolean playback = json.contains("\"playbackConfirmed\": true");
            Instant generatedAt = parseInstant(json);
            String runtimeEvidence = stringValue(json, "runtimeEvidence");
            if (!generated) {
                return new XttsSmokeTestReport(dir, text, audio, manifest, false, playback, bytes, generatedAt,
                        List.of("El WAV de prueba no existe o no tiene tamano valido."),
                        "La prueba de Voz IA avanzada existe, pero el WAV no parece valido.");
            }
            String message = playback
                    ? "Voz IA avanzada tiene prueba WAV generada y reproduccion confirmada dentro de la app."
                    : "Voz IA avanzada genero un WAV real; falta confirmar reproduccion desde la app antes de documentos largos.";
            if (!runtimeEvidence.isBlank()) {
                message = message + " " + runtimeEvidence;
            }
            return new XttsSmokeTestReport(dir, text, audio, manifest, true, playback, bytes, generatedAt, List.of(), message);
        } catch (IOException ex) {
            return XttsSmokeTestReport.failed(dir, "No se pudo leer la prueba local de Voz IA avanzada.", List.of(ex.getMessage()));
        }
    }

    public static Path smokeDirectory(Path applicationRoot) {
        return RuntimeArtifactPaths.fromRoot(applicationRoot).xttsSmokeDirectory();
    }

    private static Instant parseInstant(String json) {
        String marker = "\"generatedAt\": \"";
        int start = json.indexOf(marker);
        if (start < 0) {
            return null;
        }
        int from = start + marker.length();
        int to = json.indexOf('"', from);
        if (to <= from) {
            return null;
        }
        try {
            return Instant.parse(json.substring(from, to));
        } catch (RuntimeException ex) {
            return null;
        }
    }

    private static String stringValue(String json, String key) {
        String marker = "\"" + key + "\": \"";
        int start = json.indexOf(marker);
        if (start < 0) {
            return "";
        }
        int from = start + marker.length();
        StringBuilder value = new StringBuilder();
        boolean escaping = false;
        for (int i = from; i < json.length(); i++) {
            char c = json.charAt(i);
            if (escaping) {
                value.append(switch (c) {
                    case 'n' -> '\n';
                    case 'r' -> '\r';
                    case 't' -> '\t';
                    default -> c;
                });
                escaping = false;
                continue;
            }
            if (c == '\\') {
                escaping = true;
                continue;
            }
            if (c == '"') {
                return value.toString().strip();
            }
            value.append(c);
        }
        return "";
    }
}
