package com.marcosmoreiradev.docupodcaststudio.localmedia;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;

/**
 * Rebuilds the small, location-dependent part of a managed ComfyUI runtime.
 * Heavy models and the virtual environment itself are never copied here.
 */
final class ComfyUiRuntimePreparation {
    private ComfyUiRuntimePreparation() {
    }

    static List<String> prepare(RuntimeAssetCatalog assets) throws IOException {
        Path root = assets.root().toAbsolutePath().normalize();
        Path models = assets.require(ComfyUiImageEngine.ID, "models").toAbsolutePath().normalize();
        Path extraModelPaths = assets.require(ComfyUiImageEngine.ID, "extraModelPaths")
                .toAbsolutePath().normalize();
        requireInside(root, models);
        requireInside(root, extraModelPaths);

        ArrayList<String> changes = new ArrayList<>();
        String yaml = """
                # Generated by DocuPodcast Studio. Do not store installation-specific paths here.
                docupodcast_studio:
                  base_path: "%s"
                  checkpoints: .
                  diffusion_models: .
                  unet: .
                  vae: vae
                  text_encoders: text_encoders
                  clip: text_encoders
                  loras: loras
                """.formatted(yamlPath(models));
        if (writeAtomicallyWhenChanged(extraModelPaths, yaml)) {
            changes.add("Se regeneró extra_model_paths.yaml para " + models + ".");
        }

        Path python = assets.require(ComfyUiImageEngine.ID, "python").toAbsolutePath().normalize();
        requireInside(root, python);
        String pythonRepair = ManagedPythonEnvironmentRepair.repair(root, python, "ComfyUI");
        if (!pythonRepair.isBlank()) changes.add(pythonRepair);
        return List.copyOf(changes);
    }

    private static boolean writeAtomicallyWhenChanged(Path target, String content) throws IOException {
        byte[] expected = content.getBytes(StandardCharsets.UTF_8);
        if (Files.isRegularFile(target) && java.util.Arrays.equals(Files.readAllBytes(target), expected)) {
            return false;
        }
        Files.createDirectories(target.getParent());
        Path staged = target.resolveSibling(target.getFileName() + ".staging");
        Files.write(staged, expected);
        try {
            Files.move(staged, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
        } catch (AtomicMoveNotSupportedException ignored) {
            Files.move(staged, target, StandardCopyOption.REPLACE_EXISTING);
        } finally {
            Files.deleteIfExists(staged);
        }
        return true;
    }

    private static String yamlPath(Path path) {
        return path.toString().replace('\\', '/').replace("\"", "\\\"");
    }

    private static void requireInside(Path root, Path target) throws IOException {
        if (!target.startsWith(root)) {
            throw new IOException("La ruta administrada escapa del runtime actual: " + target);
        }
    }
}
