package com.marcosmoreiradev.docupodcaststudio.presentation.theatre;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class TheatreTextMapsSourceTest {
    @Test
    void documentShowsTextAliasesAndClearsSelectionFromWorkspaceBackground() throws Exception {
        String document = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/document/DocumentWorkspaceView.java");
        String css = read("src/main/resources/css/document/document-page.css");

        assertTrue(document.contains("IntervencionCatalogo"));
        assertTrue(document.contains("intervencionBadge"));
        assertTrue(document.contains("theatreReplicaBadge"));
        assertTrue(document.contains("paragraphContextMenu"));
        assertTrue(document.contains("Copiar texto"));
        assertTrue(document.contains("focusedTheatreSceneBlockIds"));
        assertTrue(document.contains("document-block-theatre-scene-focus"));
        assertTrue(document.contains("focusedTheatreSceneIdProperty().addListener"));
        assertTrue(document.contains("IntervencionNumberingScene.intervencionesParaEscena"));
        assertTrue(document.contains("completeSceneBoundary"));
        assertTrue(document.contains("!boundary.startId().isBlank() && !boundary.endId().isBlank()"));
        assertTrue(document.contains("Segmento de texto"));
        assertTrue(document.contains("Texto \" + (index + 1)"));
        assertTrue(document.contains("addEventFilter(MouseEvent.MOUSE_PRESSED"));
        assertTrue(document.contains("clearSelectionFromWorkspacePointerPress"));
        assertTrue(document.contains("targetInsideDocumentBlock"));
        assertTrue(document.contains("content.setMinHeight(1120)"));
        assertTrue(document.contains("documentTitleWithExtension"));
        assertTrue(css.contains("document-theatre-text-alias"));
        assertTrue(css.contains("-fx-padding: 142 12 74 12"));
        assertTrue(css.contains("-fx-padding: 78 38 74 38"));
    }

    @Test
    void theatreDockFusesSpatialAndActionMapsAndKeepsSceneFoldsLive() throws Exception {
        String dock = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreSideDock.java");
        String folds = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreSceneFoldList.java");
        String textual = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreTextualMapPanel.java");
        String emptyState = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreWorkspaceEmptyState.java");
        String sequenceCanvas = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreTextSequenceCanvas.java");
        String selectionBridge = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreInterventionSelectionBridge.java");
        String zigzag = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreZigzagLayout.java");
        String canvasSelection = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreCanvasSelectionSupport.java");
        String spatial = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreSpatialActionMapPanel.java");
        String shell = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/shell/DocuPodcastShellViewModel.java");
        String aliases = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/IntervencionCatalogo.java");
        String sceneNumbering = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/IntervencionNumberingScene.java");
        String css = read("src/main/resources/css/components/theatre-structure.css");

        assertTrue(dock.contains("new TheatreTextualMapPanel"));
        assertTrue(dock.contains("new TheatreSpatialActionMapPanel"));
        assertTrue(dock.contains("sceneBoundaryStore"));
        assertTrue(dock.contains("Mapa espacial y acciones"));
        assertFalse(dock.contains("TheatrePlaceholderPanel.actions()"));
        assertTrue(folds.contains("viewModel.theatreActs()"));
        assertTrue(folds.contains("viewModel.theatreScenes()"));
        assertTrue(folds.contains("Nuevo acto"));
        assertTrue(folds.contains("Agregar escena"));
        assertTrue(folds.contains("TheatreWorkspaceEmptyState.noActsMessage"));
        assertTrue(folds.contains("TheatreWorkspaceEmptyState.noScenesMessage"));
        assertTrue(folds.contains("showActEditor"));
        assertTrue(folds.contains("showSceneEditor"));
        assertTrue(folds.contains("deleteTheatreScene"));
        assertTrue(folds.contains("currentScriptProperty().addListener"));
        assertTrue(folds.contains("dirtyProperty().addListener"));
        assertTrue(textual.contains("clic derecho en una intervencion"));
        assertTrue(textual.contains("theatre-textual-map-scroll"));
        assertFalse(textual.contains("aliasStrip"));
        assertFalse(textual.contains("Prepara la lectura para ver T1, T2"));
        assertTrue(textual.contains("Establecer texto inicial"));
        assertTrue(textual.contains("Establecer texto final"));
        assertTrue(textual.contains("TheatreTextSequenceCanvas"));
        assertTrue(textual.contains("TheatreWorkspaceEmptyState.interventionSequenceMessage"));
        assertTrue(textual.contains("TheatreWorkspaceEmptyState.preparationNotice"));
        assertTrue(textual.contains("TheatreInterventionSelectionBridge.bind"));
        assertTrue(textual.contains("TheatreInterventionSelectionBridge.blockSelector(viewModel, scene)"));
        assertTrue(emptyState.contains("fuente primaria"));
        assertTrue(emptyState.contains("No hay intervenciones teatrales detectables"));
        assertTrue(emptyState.contains("Lectura no preparada"));
        assertTrue(textual.contains("showEmotionEditor"));
        assertTrue(textual.contains("assignEmotionStyleToDocumentBlock"));
        assertTrue(textual.contains("ComboBox<VoiceReferenceTone>"));
        assertTrue(textual.contains("VoiceReferenceTone.values()"));
        assertTrue(textual.contains("selected.layerTargetId()"));
        assertTrue(textual.contains("seleccionado para texto inicial de escena"));
        assertTrue(textual.contains("idParaEscena(boundary.startId())"));
        assertTrue(textual.contains("BoundaryCapture.START"));
        assertTrue(textual.contains("BoundaryCapture.END"));
        assertTrue(textual.contains("selectedDocumentBlockIdProperty().addListener"));
        assertTrue(textual.contains("selectedDocumentTextRangeProperty().addListener"));
        assertTrue(sceneNumbering.contains("indiceBaseNumeracion"));
        assertTrue(sceneNumbering.contains("globalIndex - baseIndex + 1"));
        assertTrue(sceneNumbering.contains("intervencionesParaEscena"));
        assertTrue(spatial.contains("TheatreStageGeometry"));
        assertTrue(spatial.contains("Mapa espacial no configurado."));
        assertTrue(spatial.contains("FlowPane"));
        assertTrue(spatial.contains("saveTheatreTextActionPlacement"));
        assertTrue(spatial.contains("markerParticipants"));
        assertFalse(spatial.contains("SPATIAL_REFERENCE_PATH"));
        assertTrue(spatial.contains("STAGE_LOCATIONS"));
        assertTrue(spatial.contains("hacia el publico"));
        assertTrue(spatial.contains("extra diegetico"));
        assertTrue(spatial.contains("diegetico"));
        assertTrue(spatial.contains("Preservar las posiciones de los personajes del texto anterior"));
        assertTrue(spatial.contains("mostrarEditorAccion"));
        assertTrue(spatial.contains("drawSpatialOverlay"));
        assertTrue(spatial.contains("drawCharacterLocationLabels"));
        assertTrue(spatial.contains("TheatreSpatialIconSet.image"));
        assertTrue(spatial.contains("TheatreSpatialRoleIcon"));
        assertTrue(spatial.contains("MarkerGroup"));
        assertTrue(spatial.contains("destinationLocations"));
        assertTrue(spatial.contains("SPATIAL_MARKER_SIZE = 101.0"));
        assertTrue(spatial.contains("SPATIAL_ARROW_TRIM_FACTOR = 0.56"));
        assertTrue(spatial.contains("SPATIAL_SELF_LOOP_SCALE_FACTOR = 0.34"));
        assertTrue(spatial.contains("SPATIAL_SELF_LOOP_RIGHT_OFFSET_FACTOR = 0.44"));
        assertTrue(spatial.contains("SPATIAL_SELF_LOOP_MARKER_LEFT_SHIFT_FACTOR = 0.10"));
        assertTrue(spatial.contains("Interaccion de personajes"));
        assertTrue(spatial.contains("Ubicacion de personajes en el escenario"));
        assertTrue(spatial.contains("ALL_REMAINING_TARGET = \"Todos los personajes restantes\""));
        assertTrue(spatial.contains("ABSENT_LOCATION = \"no presente\""));
        assertTrue(spatial.contains("Map<String, CheckBox> interactionInputs"));
        assertTrue(spatial.contains("bindPresenceToInteractionTargets"));
        assertTrue(spatial.contains("updateInteractionTargetAvailability"));
        assertTrue(spatial.contains("selectedInteractionTargets(interactionInputs, characterLocationInputs, speakerName)"));
        assertTrue(spatial.contains("locationCombo(existing.characterLocations().getOrDefault(character, STAGE_LOCATIONS.get(4)), true)"));
        assertTrue(spatial.contains("actionReceiverOptions(speakerName)"));
        assertTrue(spatial.contains(".filter(name -> !isSpecialTarget(name))"));
        assertTrue(spatial.contains(".filter(name -> speaker.isBlank() || !name.equalsIgnoreCase(speaker))"));
        assertTrue(spatial.contains("isAbsentLocation(location)"));
        assertFalse(spatial.contains("formRow(\"Flecha hacia\""));
        assertFalse(spatial.contains("ComboBox<String> interaction"));
        assertTrue(spatial.contains("rgba(15, 23, 42, 0.76)"));
        assertTrue(spatial.contains("Color.WHITE"));
        assertFalse(spatial.contains("rgba(34, 197, 94"));
        assertFalse(spatial.contains("strokeRoundRect(point.x() - 16"));
        assertFalse(spatial.contains("gc.strokeOval(origin.x()"));
        assertTrue(spatial.contains("drawSelfLoop"));
        assertTrue(spatial.indexOf("if (icon != null)") < spatial.indexOf("gc.fillOval(point.x()"));
        assertTrue(spatial.contains("TextActionPlacement"));
        assertTrue(spatial.contains("SPATIAL_IMAGE_FIT_WIDTH = 760.0"));
        assertTrue(spatial.contains("frame.setMaxSize(Region.USE_PREF_SIZE, Region.USE_PREF_SIZE)"));
        assertTrue(spatial.contains("theatre-spatial-overlay-canvas"));
        assertTrue(spatial.contains("Ver mapa en pantalla completa"));
        assertTrue(spatial.contains("Modo acompañante:"));
        assertTrue(spatial.contains("Fragmentos visuales"));
        assertTrue(spatial.contains("Fotos de personajes"));
        assertTrue(spatial.contains("Sin acompañante"));
        assertTrue(spatial.contains("prepareSpatialVideoFrames"));
        assertFalse(spatial.contains("resolveActivePlacementAlias"));
        assertFalse(spatial.contains("showSpatialFullscreen"));
        assertFalse(spatial.contains("setFullScreen(true)"));
        assertFalse(spatial.contains("FloatingReadingControlBar"));
        assertTrue(spatial.contains("TheatreTextSequenceCanvas"));
        assertTrue(spatial.contains("theatre-action-canvas-scroll"));
        assertTrue(spatial.contains("drawArrow"));
        assertTrue(spatial.contains("heightFor"));
        assertTrue(spatial.contains("selectedIntervencion"));
        assertTrue(spatial.contains("TheatreInterventionSelectionBridge.bind"));
        assertTrue(spatial.contains("TheatreInterventionSelectionBridge.blockSelector(viewModel, scene)"));
        assertTrue(selectionBridge.contains("selectedDocumentBlockIdProperty().addListener"));
        assertTrue(selectionBridge.contains("focusedTheatreSceneIdProperty().addListener"));
        assertTrue(selectionBridge.contains("viewModel.focusTheatreScene(scene.id())"));
        assertTrue(selectionBridge.contains("IntervencionNumberingScene.intervencionesParaEscena"));
        assertTrue(sequenceCanvas.contains("TheatreCanvasSelectionSupport.clearOnEmptyPrimaryClick(event, selectedIntervencion, blockSelection)"));
        assertTrue(zigzag.contains("drawEditActionButton"));
        assertTrue(zigzag.contains("drawDownloadActionButton"));
        assertTrue(zigzag.contains("ACTION_BUTTON_SIZE = 16"));
        assertTrue(sequenceCanvas.contains("TheatreZigzagLayout.drawEditActionButton(gc, editX, editY)"));
        assertTrue(sequenceCanvas.contains("TheatreZigzagLayout.drawDownloadActionButton(gc, downloadX, downloadY)"));
        assertTrue(spatial.contains("TheatreZigzagLayout.drawEditActionButton(gc, editX, editY)"));
        assertFalse(sequenceCanvas.contains("fillText(\"E\""));
        assertFalse(sequenceCanvas.contains("fillText(\"D\""));
        assertFalse(spatial.contains("fillText(\"E\""));
        assertFalse(spatial.contains("fillText(\"D\""));
        assertTrue(canvasSelection.contains("static boolean clearOnEmptyPrimaryClick"));
        assertTrue(canvasSelection.contains("MouseButton.PRIMARY"));
        assertTrue(canvasSelection.contains("blockSelection.accept(\"\")"));
        assertTrue(spatial.contains("if (activeAlias == null || activeAlias.isBlank())"));
        assertTrue(spatial.contains("return List.of();"));
        assertTrue(shell.contains("if (normalized.isBlank())"));
        assertTrue(shell.contains("selectedScriptSegmentId.set(\"\")"));
        assertTrue(shell.contains("actualizarFrameActivo();"));
        assertTrue(spatial.contains("TheatreZigzagLayout.speakerLabel"));
        assertTrue(spatial.contains("TheatreZigzagLayout.WIDTH"));
        assertTrue(spatial.contains("setPrefViewportHeight(320)"));
        assertTrue(css.contains(".theatre-action-canvas-scroll"));
        assertTrue(css.contains(".theatre-spatial-overlay-canvas"));
        assertFalse(css.contains("-fx-min-height: 360px"));
        assertTrue(css.contains("-fx-min-height: 300px"));
        assertTrue(aliases.contains("esCueTeatral"));
        assertTrue(aliases.contains("ACOTACION"));
        assertTrue(aliases.contains("ESCENA"));

        String fullscreenView = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/presentation/theatre/TheatreFullscreenMapView.java");
        assertTrue(fullscreenView.contains("setFullScreen(true)"));
        assertTrue(fullscreenView.contains("theatre-fullscreen-playbar"));
        assertTrue(fullscreenView.contains("FloatingReadingControlBar"));
        assertFalse(fullscreenView.contains("transportButton("));
        assertTrue(fullscreenView.contains("theatre-fullscreen-fragments-layout"));
        assertTrue(fullscreenView.contains("theatre-fullscreen-map-only"));
        assertTrue(fullscreenView.contains("resizeMapCanvas"));
        assertTrue(fullscreenView.contains("\"none\".equals(mode)"));
        assertTrue(fullscreenView.contains("bindMapPaneToHost(centerHost, mapPane"));
        assertTrue(fullscreenView.contains("StackPane.setMargin(mapPane"));
        assertTrue(fullscreenView.contains("centerHost.heightProperty().subtract"));
        assertTrue(fullscreenView.contains("computePrefWidth"));
        assertTrue(fullscreenView.contains("computeMinHeight"));
        assertTrue(fullscreenView.contains("Personajes presentes"));
        assertTrue(fullscreenView.contains("Mapa espacial no configurado"));
        assertTrue(fullscreenView.contains("TheatreSpatialIconSet.image"));
        assertTrue(fullscreenView.contains("TheatreSpatialRoleIcon"));
        assertTrue(fullscreenView.contains("MarkerGroup"));
        assertTrue(fullscreenView.contains("destinationLocations"));
        assertTrue(fullscreenView.contains("MARKER_SIZE = 118.0"));
        assertTrue(fullscreenView.contains("ARROW_TRIM_FACTOR = 0.56"));
        assertTrue(fullscreenView.contains("SELF_LOOP_SCALE_FACTOR = 0.34"));
        assertTrue(fullscreenView.contains("SELF_LOOP_RIGHT_OFFSET_FACTOR = 0.44"));
        assertTrue(fullscreenView.contains("SELF_LOOP_MARKER_LEFT_SHIFT_FACTOR = 0.10"));
        assertTrue(fullscreenView.contains("isAbsentLocation"));
        assertTrue(fullscreenView.contains("isCharacterAbsent"));
        assertTrue(fullscreenView.contains("drawSelfLoop"));
        assertTrue(fullscreenView.contains("if (activeAlias == null || activeAlias.isBlank())"));
        assertTrue(fullscreenView.contains("return Map.of();"));
        assertFalse(fullscreenView.contains("rgba(34, 197, 94"));
        assertFalse(fullscreenView.contains("gc.strokeOval(origin.x()"));
        assertTrue(fullscreenView.indexOf("if (icon != null)") < fullscreenView.indexOf("gc.fillOval(point.x()"));
        assertFalse(fullscreenView.contains("/examples/aviadores-comicos/assets/mapas/mapa-espacial.png"));

        String stageGeometry = read("src/main/java/com/marcosmoreiradev/docupodcaststudio/application/video/TheatreStageGeometry.java");
        assertTrue(stageGeometry.contains("case \"extra diegetico\" -> new StagePoint(665, 105)"));
        assertFalse(stageGeometry.contains("case \"extra diegetico\" -> new StagePoint(690, 68)"));
    }

    private static String read(String path) throws Exception {
        return Files.readString(Path.of(path));
    }
}
