package com.marcosmoreiradev.docupodcaststudio.application.runtime;

/**
 * Auditable descriptor for a motor/runtime artifact.
 *
 * <p>T119C intentionally separates artifact identity from the actual files that may be
 * user-provided, bundled, or generated by setup assistants. RC-FINAL must replace pending
 * checksums with concrete SHA-256 values before distribution.</p>
 */
public record EngineArtifactDescriptor(
        String id,
        String displayName,
        String engine,
        EngineArtifactKind kind,
        String expectedPath,
        boolean requiredForFinalRc,
        boolean redistributedByDefault,
        boolean userProvidedAllowed,
        String licenseName,
        String sourceUrl,
        String sha256,
        String notes
) {
    public static final String PENDING_SHA256 = "PENDING_SHA256_UNTIL_ARTIFACT_LOCKED";

    public EngineArtifactDescriptor {
        if (id == null || id.isBlank()) {
            throw new IllegalArgumentException("id is required");
        }
        if (displayName == null || displayName.isBlank()) {
            throw new IllegalArgumentException("displayName is required");
        }
        if (engine == null || engine.isBlank()) {
            throw new IllegalArgumentException("engine is required");
        }
        if (kind == null) {
            throw new IllegalArgumentException("kind is required");
        }
        expectedPath = expectedPath == null ? "" : expectedPath.trim();
        licenseName = licenseName == null || licenseName.isBlank() ? "Pendiente de confirmar" : licenseName.trim();
        sourceUrl = sourceUrl == null ? "" : sourceUrl.trim();
        sha256 = sha256 == null || sha256.isBlank() ? PENDING_SHA256 : sha256.trim();
        notes = notes == null ? "" : notes.trim();
    }

    public boolean hasConcreteSha256() {
        return sha256 != null && !sha256.isBlank() && !PENDING_SHA256.equals(sha256);
    }

    public boolean licensePending() {
        return licenseName.toLowerCase().contains("pendiente");
    }
}
